import React, { useEffect, useMemo, useState } from 'react';
import { FileCard, Header, Group, Closing, Callout } from './ui';
import assets from './data/assets.json';
import './style.css';
import previewArt from './preview-art.png';

import {Holding,Price,Point,DEMO,money,time,fetchPrice,walletHoldings,validSolanaAddress,markExplain} from './services/market';
import {getQuote,Quote} from './services/jupiter';
import {WalletShell,WalletConnect,useWallet} from './wallet/Wallet';
const POLL_MS=45_000;
function Sparkline({points}:{points:Point[]}){
  if(points.length<2)return <p className="trend-empty">A line appears after the next live check. Leave this page open to watch the gap.</p>;
  const values=points.map(p=>p.gap),lo=Math.min(...values),hi=Math.max(...values),range=Math.max(hi-lo,.02);
  const path=points.map((p,i)=>`${8+i*224/(points.length-1)},${48-(p.gap-lo)/range*36}`).join(' ');
  return <div className="trend-chart"><svg viewBox="0 0 240 56" role="img" aria-label={`Observed venue gap moved from ${values[0].toFixed(2)} to ${values[values.length-1].toFixed(2)} percent over ${points.length} checks`} preserveAspectRatio="none"><line x1="8" x2="232" y1="48" y2="48" stroke="#dbe8e2"/><polyline fill="none" stroke="#198270" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" points={path}/><circle cx="232" cy={path.split(' ').at(-1)?.split(',')[1]} r="3.5" fill="#198270"/></svg><div className="trend-times"><span>{time(points[0].at)}</span><span>{time(points[points.length-1].at)}</span></div></div>;
}
function ActOnIt({mint,symbol}:{mint:string;symbol:string}){
 const [direction,setDirection]=useState<'buy'|'sell'>('buy');const [quote,setQuote]=useState<Quote>();const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 async function load(next:'buy'|'sell'=direction){setDirection(next);setLoading(true);setError('');setQuote(undefined);try{setQuote(await getQuote(mint,next))}catch(e:any){setError(e.message||'Quote unavailable')}finally{setLoading(false)}}
 return <section className="act-on-it"><h4>Act on it <small>Jupiter route, separate from the pools above</small></h4><p>See an indicative swap route. Execution is coming; you cannot trade here yet.</p><div className="quote-actions"><button type="button" onClick={()=>load('buy')} disabled={loading}>Quote 10 USDC → {symbol}</button><button type="button" onClick={()=>load('sell')} disabled={loading}>Quote 0.01 {symbol} → USDC</button></div>{loading&&<p role="status">Fetching Jupiter route…</p>}{error&&<p className="card-error" role="status">{error}</p>}{quote&&<div className="quote-result" role="status"><strong>{quote.inputAmount} {direction==='buy'?'USDC':symbol} → about {quote.outputAmount.toLocaleString('en-US',{maximumFractionDigits:6})} {direction==='buy'?symbol:'USDC'}</strong><small>Route: {quote.route.map(r=>`${r.venue} (${r.percent}%)`).join(' + ')||'not specified'} · Price impact: {quote.priceImpactPct.toFixed(3)}% · Max slippage: {quote.slippageBps/100}% · Minimum after slippage: {quote.minOutputAmount.toLocaleString('en-US',{maximumFractionDigits:6})} {direction==='buy'?symbol:'USDC'}</small><small>Integrator fee: none charged in this read-only preview. Route pool fees are included in Jupiter's quoted output; network transaction fees may apply to a future trade. Quote checked {time(quote.quotedAt)}. Not executable, not a promise of fill.</small></div>}</section>
}
function Card({holding,price,points,refreshing}:{holding:Holding;price?:Price;points:Point[];refreshing:boolean}) {
 const [expanded,setExpanded]=useState(false);const a=assets.find(a=>a.symbol===holding.symbol)!;const diff=price?.second!==undefined&&price?.dex!==undefined?(price.dex/price.second-1)*100:undefined;
 return <article className={`asset-card ${expanded?'is-open':''}`}><div className="asset-head"><div><span className="ticker">{a.symbol}</span><span className="asset-name">{a.name}</span></div><span className="amount">{holding.amount.toLocaleString('en-US',{maximumFractionDigits:6})} tokens</span></div>
 <div className="price-grid"><div><span className="kicker">Pool A / token</span><strong>{!price?'Loading…':money(price.dex)}</strong><small>{!price?'Fetching live pool':price.pool?`${price.pool.name} · ${price.pool.pair.slice(0,5)}…${price.pool.pair.slice(-4)}`:'No matching live USDC pool'}</small></div><div><span className="kicker">Pool B / token</span><strong>{!price?'Loading…':money(price.second)}</strong><small>{!price?'Fetching live pool':price.secondPool?`${price.secondPool.name} · ${price.secondPool.pair.slice(0,5)}…${price.secondPool.pair.slice(-4)}`:'No second live USDC pool'}</small></div></div>
 <div className="gap"><div><span className="kicker">Observed gap</span><strong className={diff!==undefined&&Math.abs(diff)>=.15?'alert':''}>{diff===undefined?'—':`${diff>=0?'+':''}${diff.toFixed(2)}%`}</strong></div><p>{markExplain(price)}</p></div>
 {price?.stale&&<p className="card-error">Last good quote, stale. Refresh failed: {price.error}</p>}{price?.error&&!price.stale&&<p className="card-error">{price.error} Try Refresh prices.</p>}
 <button className="detail-toggle" type="button" aria-expanded={expanded} aria-controls={`detail-${a.symbol}`} onClick={()=>setExpanded(v=>!v)}>{expanded?'Hide market detail −':'Explore market detail +'}<span aria-hidden="true">↗</span></button>
 {expanded&&<div className="card-detail" id={`detail-${a.symbol}`}><div className="detail-title"><span className="kicker">Live gap trail</span><span>{points.length} {points.length===1?'check':'checks'} · 45-sec auto-refresh</span></div><Sparkline points={points}/><div className="detail-facts"><div><span>Pool A liquidity</span><strong>{money(price?.pool?.liquidity)}</strong></div><div><span>Pool B liquidity</span><strong>{money(price?.secondPool?.liquidity)}</strong></div></div><p className="detail-disclaimer">DexScreener pool prices are not Jupiter routes or executable prices. Only checks made while this page is open.</p>{price&&<small className="detail-checked">Quote source checked {time(price.checked)}{price.stale?' · stale':''}{refreshing?' · checking again…':''}</small>}</div>}
 {price?.pool&&<div className="pool-links"><a href={price.pool.url} target="_blank" rel="noopener noreferrer" aria-label={`Inspect ${a.symbol} Pool A on DexScreener`}>Pool A ({price.pool.name}) ↗</a>{price.secondPool&&<a href={price.secondPool.url} target="_blank" rel="noopener noreferrer" aria-label={`Inspect ${a.symbol} Pool B on DexScreener`}>Pool B ({price.secondPool.name}) ↗</a>}</div>}
 <ActOnIt mint={a.mint} symbol={a.symbol}/>
 </article>
}
export function App(){
  const {publicKey}=useWallet();const [connectedBefore,setConnectedBefore]=useState(false);const [input,setInput]=useState('');const [address,setAddress]=useState('');const [mode,setMode]=useState<'demo'|'wallet'>('demo');const [holdings,setHoldings]=useState<Holding[]>(DEMO);const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [prices,setPrices]=useState<Record<string,Price>>({});const [history,setHistory]=useState<Record<string,Point[]>>({});const [refreshing,setRefreshing]=useState(true);const [tick,setTick]=useState(0);const [lastChecked,setLastChecked]=useState<number>();const [selected,setSelected]=useState('ALL');
  useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==='visible')setTick(n=>n+1)},POLL_MS);const onVisible=()=>{if(document.visibilityState==='visible')setTick(n=>n+1)};document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',onVisible)}},[]);
  useEffect(()=>{let cancelled=false;setRefreshing(true);const relevant=assets.filter(a=>holdings.some(h=>h.symbol===a.symbol));if(!relevant.length){setRefreshing(false);return}Promise.all(relevant.map(async a=>[a.symbol,await fetchPrice(a)] as const)).then(rows=>{if(cancelled)return;const now=Date.now();setPrices(previous=>Object.fromEntries(rows.map(([symbol,p])=>{const prior=previous[symbol];return [symbol,p.error&&prior?.dex!==undefined?{...prior,stale:true,error:p.error}:p]})));setLastChecked(now);setHistory(previous=>{const next={...previous};for(const [symbol,p] of rows){if(p.dex===undefined||p.second===undefined)continue;const point={at:now,gap:(p.dex/p.second-1)*100};const old=next[symbol]||[];next[symbol]=[...old,point].slice(-20)}return next});setRefreshing(false);setMessage(rows.every(([,p])=>p.error)?'Market quotes are temporarily unavailable. Try Refresh prices.':`Live check complete: ${rows.filter(([,p])=>p.dex!==undefined&&p.second!==undefined).length} of ${rows.length} comparisons available.`)}).catch(()=>{if(!cancelled){setRefreshing(false);setMessage('Market data did not answer. Try Refresh prices.')}});return()=>{cancelled=true}},[holdings,tick]);
  const count=useMemo(()=>holdings.filter(h=>!prices[h.symbol]?.stale&&prices[h.symbol]?.dex!==undefined&&prices[h.symbol]?.second!==undefined).length,[prices,holdings]);
  async function inspect(e:React.FormEvent){e.preventDefault();const value=input.trim();if(!validSolanaAddress(value)){setMessage('Enter a valid Solana public wallet address (base58, 32 bytes).');return}setLoading(true);setMessage('Checking SPL Token and Token-2022 balances on Solana mainnet…');try{const h=await walletHoldings(value);setAddress(value);setMode('wallet');setSelected('ALL');setHoldings(h);setPrices({});setHistory({});setLastChecked(undefined);setMessage(h.length?'Balances found. Fetching live pool quotes…':'No supported xStocks with a positive balance in this wallet. Try the example.')}catch{setMessage('Wallet lookup is temporarily unavailable. Your wallet was not changed; try again or use the example.')}finally{setLoading(false)}}
  useEffect(()=>{if(!publicKey){if(connectedBefore){setConnectedBefore(false);setMode('demo');setHoldings(DEMO);setAddress('');setSelected('ALL');setMessage('Wallet disconnected. Example portfolio restored.')}return}setConnectedBefore(true);const value=publicKey.toBase58();setInput(value);let cancelled=false;setLoading(true);setMessage('Loading connected wallet xStock balances…');walletHoldings(value).then(h=>{if(cancelled)return;setAddress(value);setMode('wallet');setSelected('ALL');setHoldings(h);setPrices({});setHistory({});setLastChecked(undefined);setMessage(h.length?'Connected wallet balances loaded. Fetching live pool quotes…':'Connected wallet holds no supported xStocks. Use the example to explore quotes.');}).catch(()=>{if(!cancelled)setMessage('Connected wallet balance lookup is unavailable right now. You can retry with Inspect wallet or use the example.');}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[publicKey]);
  function demo(){setMode('demo');setSelected('ALL');setAddress('');setHoldings(DEMO);setPrices({});setHistory({});setLastChecked(undefined);setMessage('Example balances loaded. Fetching live pool quotes…');setTick(n=>n+1)}
  function selectAsset(symbol:string){setSelected(symbol);document.getElementById('compare')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function refresh(){if(refreshing)return;setMessage('Checking live pool quotes…');setTick(n=>n+1)}
  return <FileCard>
    <Header title="Why is my xStock a different price?" fact="A live venue-gap lens for tokenized stocks on Solana" intro="The same token can show two prices at the same moment. See the onchain venue gap, then learn why it happens." />
    <div className="hero"><img className="hero-art" src={previewArt} alt="Abstract overlapping market orbits, an illustration of two price paths"/><div className="hero-motif" aria-hidden="true"><span className="signal one"/><span className="signal two"/><span className="signal three"/><i/><b>≠</b></div><div className="hero-copy"><span className="eyebrow">DOUBLETAKE · SEE THE TRUTH, THEN ACT ON IT</span><p>One token. Two pools. <em>Which price is real?</em></p></div></div>
    <nav className="journey" aria-label="How to explore DoubleTake"><div><b>01</b><a href="#choose">Pick a stock</a><small>Try the fictional example</small></div><div><b>02</b><a href="#compare">Compare two pools</a><small>Real prices, same token</small></div><div><b>03</b><a href="#explain">Make sense of it</a><small>Know what the gap means</small></div></nav>
    <div id="choose" className="anchor"/>
    <Group label="Start here · 01" heading><p className="journey-intro">Choose a stock below to follow its prices, or load the full example portfolio. It uses made-up balances, but the prices come from live Solana markets. Connect a wallet or inspect a public address without signing. Neither can make a trade in this preview.</p><p className="lead">Enter a public Solana address to inspect supported xStock balances. Wallet balances are read through our server-side Solana RPC route. If RPC is busy, use the example instead.</p><WalletConnect/><form onSubmit={inspect} className="wallet-form"><label htmlFor="wallet">Public wallet address</label><div className="input-row"><input id="wallet" value={input} onChange={e=>setInput(e.target.value)} spellCheck={false} autoComplete="off" placeholder="Paste a Solana mainnet address"/><button type="submit" disabled={loading}>{loading?'Checking…':'Inspect wallet'}</button></div></form><div className="quick-start"><span className="kicker">One-tap demo · choose an asset</span><div className="quick-buttons">{DEMO.map(h=><button type="button" key={h.symbol} onClick={()=>{if(mode!=='demo'){demo();setTimeout(()=>selectAsset(h.symbol),0)}else selectAsset(h.symbol)}}>{h.symbol}<small>{assets.find(a=>a.symbol===h.symbol)?.name}</small></button>)}</div></div><div className="demo-row"><span>See everything?</span><button type="button" onClick={demo}>Explore example portfolio ↗</button></div>{message&&<p className="status" role="status">{message}</p>}</Group>
    <div id="compare" className="anchor"/><Group label="Compare · 02" heading><p className="journey-intro">One token can have different prices in two trading pools. Pool A and Pool B are the two deepest pools with the verified USDC mint that we found. Tap any card to see liquidity and watch the gap change while this tab stays open.</p><div className="section-bar"><span className="mode">{mode==='demo'?'EXAMPLE PORTFOLIO':'LIVE WALLET BALANCES'}</span><button type="button" onClick={refresh} disabled={refreshing} aria-busy={refreshing}>{refreshing?'Checking prices…':'Refresh prices ↻'}</button></div>{mode==='wallet'&&<p className="address">{address}</p>}{holdings.length>1&&<div className="asset-filter" role="group" aria-label="Choose an asset to compare"><button type="button" aria-pressed={selected==='ALL'} onClick={()=>setSelected('ALL')}>All</button>{holdings.map(h=><button type="button" key={h.symbol} aria-pressed={selected===h.symbol} onClick={()=>setSelected(h.symbol)}>{h.symbol}</button>)}</div>}{holdings.length?<><div className="holdings">{holdings.filter(h=>selected==='ALL'||selected===h.symbol).map(h=><Card key={h.symbol} holding={h} price={prices[h.symbol]} points={history[h.symbol]||[]} refreshing={refreshing}/>)}</div><p className="freshness">{lastChecked?`${count}/${holdings.length} paired quotes · Checked ${time(lastChecked)}${refreshing?' · Refreshing…':''}`:'Fetching live quotes…'} · Indicative, not executable prices</p></>:<Callout title="Nothing to compare yet">This wallet has no positive balance among the five currently supported xStocks. Try the example or another public address.</Callout>}</Group>
    <div id="explain" className="anchor"/><Group label="Understand · 03" heading><p className="journey-intro">A gap is the percentage difference between these two pool quotes, not a profit forecast. Open either pool link to check the underlying market yourself.</p><div className="reasons"><div><span>01</span><h3>Different clocks</h3><p>US shares have exchange hours, while Solana pools can trade outside them. A token need not match a closed-market share quote.</p></div><div><span>02</span><h3>Different markets</h3><p>Two Solana USDC pools can post different prices for the same token. This screen compares venues, not a US share price.</p></div><div><span>03</span><h3>Different depth</h3><p>Thin pools, spreads and trade size can move a fill away from a screen quote. Check liquidity before drawing conclusions.</p></div></div></Group>
    <Group label="About this prototype" heading><p className="lead">The example holdings are fictional, but pool prices are fetched live from DexScreener. The gap trail is sampled every 45 seconds while this page is open, held only in memory, and starts fresh on reload. For each verified xStock Solana mint, we compare the two USDC pools with the highest reported USD liquidity above $1,000. Wallet balances are queried through a read-only server function for SPL Token and Token-2022. Connecting a wallet never signs a transaction. Five mints are recognized: AAPLx, TSLAx, NVDAx, MSFTx and GOOGLx. Other assets are ignored, not counted as zero.</p><p className="lead">DexScreener pool prices are distinct from Jupiter's indicative swap route. Neither is a US share price, issuer indicative value, redemption price, or promise of execution. Pyth's live price API requires an API key; this prototype does not claim Pyth bounty eligibility.</p><div className="source-links"><a href="https://docs.xstocks.fi/apis/openapi.md" target="_blank" rel="noopener noreferrer">xStocks mint registry ↗</a><a href="https://docs.pyth.network/price-feeds/core/upgrade/preparing" target="_blank" rel="noopener noreferrer">Pyth access note ↗</a><a href="https://solana.com/docs/rpc/http/gettokenaccountsbyowner" target="_blank" rel="noopener noreferrer">Solana RPC ↗</a><a href="https://docs.dexscreener.com/api/reference" target="_blank" rel="noopener noreferrer">DEX market data ↗</a></div></Group>
    <Closing>DoubleTake · Built for the Solana hackathon · Read-only preview · Wallet connection and indicative routes only · No trades or wallet signatures.</Closing>
  </FileCard>
}

export default function TradingApp(){return <WalletShell><App/></WalletShell>}
